### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [kratosvn/bet188#1]
Hi,<br><br>url : https://github.com/kratosvn/bet188/blob/dd6ff420a08279aaacb11e8fcb7db5ebfb8e7324/config/database.php <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by kratosvn** [comment]
thank for your suggest.
